function makeTrialStructForFinalExperiment(subjectName,iterationNumber, condition)

% This function makes trial structs for all three cases.
%
% subjectName = Subject Name Ex. 'Vijay'
% numberOfStructs = number of trial structs required, Ex 3
%
% The trial structs will be saved in
%           LightnessCasesForExperiment/StimuliFixedFlatTargetShapeFixedIlluminantFixedBkGnd
%           LightnessCasesForExperiment/StimuliFixedFlatTargetShapeFixedIlluminantBetweentrialBkGndVariation
%           LightnessCasesForExperiment/StimuliFixedFlatTargetShapeFixedIlluminantWithintrialBkGndVariation
%
% Vijay Singh wrote this. Dec 12 2018


nameOfTrialStruct = [subjectName,'_Iteration_',num2str(iterationNumber)];

switch condition
    case '1'

makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantFixedBkGnd',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',true);

    case '2'
makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantBetweentrialBkGndVariation',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',true);

case '2a'
makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantBetweentrialBkGndVariationNoReflection',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',true);

case '3'
makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantWithintrialBkGndVariation',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',false);

case '3a'
makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantWithintrialBkGndVariationNoReflection',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',false);

end
end