% demoForCase1 - Fixed background, Random Same background, random different background

% 1 Fixed BackGround
runLightnessExperiment('directoryName', 'FlatFixedTargetShapeFixedIlluminantFixedBkGnd',...
    'nameOfTrialStruct', 'Demo1', ...
    'controlSignal', 'gamePad', ...
    'interval1Key', 'GP:1', ...
    'interval2Key', 'GP:2', ...
    'feedback', 1, ...
    'subjectName', 'Demo1');

%%
% 2 Random Same background
runLightnessExperiment('directoryName', 'StimuliFixedFlatTargetShapeFixedIlluminantRandomBkGndFixedIntervals_test1',...
    'nameOfTrialStruct', 'Demo1', ...
    'controlSignal', 'gamePad', ...
    'interval1Key', 'GP:1', ...
    'interval2Key', 'GP:2', ...
    'feedback', 1, ...
    'subjectName', 'Demo1');

%%
% 3 Random different background
runLightnessExperiment('directoryName', 'StimuliFixedFlatTargetShapeFixedIlluminantRandomBkGndAcrossIntervals_test1',...
    'nameOfTrialStruct', 'Demo1', ...
    'controlSignal', 'gamePad', ...
    'interval1Key', 'GP:1', ...
    'interval2Key', 'GP:2', ...
    'feedback', 1, ...
    'subjectName', 'Demo1');