function runGame

nameOfTrialStruct = 'TrialStructForArcade';
scaleFactor = 5.4;

makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_1_00_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 5,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:2:11), ...
            'comparisionTargetSameSpectralShape',false);
               
        
runExperimentArcade('directoryName', 'StimuliCondition2_covScaleFactor_1_00_NoReflection',...
    'nameOfTrialStruct', nameOfTrialStruct, ...
    'controlSignal', 'gamePad', ...
    'interval1Key', 'GP:UpperLeftTrigger', ...
    'interval2Key', 'GP:UpperRightTrigger', ...
    'feedback', 1, ...
    'subjectName', nameOfTrialStruct, ...
    'scaleFactor', scaleFactor);

pathToTrialStruct = fullfile(getpref('VirtualWorldPsychophysics','stimulusInputBaseDir'),...
    'StimuliCondition2_covScaleFactor_1_00_NoReflection',[nameOfTrialStruct '.mat']);
delete(pathToTrialStruct);

end