runLightnessExperiment('directoryName', 'RandomTargetShapeFixedIlluminantFixedBkGnd',...
        'nameOfTrialStruct', 'exampleTrial', ...
        'nameOfLMSStruct', 'LMSStruct', ...
        'subjectName', 'testSubject');