%%testMakeTrialStruct test script for makeTrialStruct function

makeTrialStruct('directoryName','RandomTargetShapeFixedIlluminantFixedBkGnd',...
    'LMSstructName', 'LMSStruct_dY0_01',...
    'outputFileName', 'TestDifferentSpectralShape2',...
    'nBlocks', 3,...
    'stdYIndex', 21, ...
    'cmpYIndex', (21), ...
    'comparisionTargetSameSpectralShape',false);