runLightnessExperiment('directoryName', 'FixedTargetShapeFixedIlluminantFixedBkGnd',...
        'nameOfTrialStruct', 'exampleTrial', ...
        'controlSignal', 'keyboard', ...
        'interval1Key', '1', ...
        'interval2Key', '2', ...
        'nameOfLMSStruct', 'LMSStruct', ...
        'subjectName', 'testSubject');
    
% mglClose;  ListenChar(0);