%%testMultispectralStructToLMSStruct Example to run multispectralStructToLMSStruct function

multispectralStructToLMSStruct(...
    'multipsectralStructFolder','FixedTargetShapeFixedIlluminantFixedBkGnd',...
    'LMSStructFolder','FixedTargetShapeFixedIlluminantFixedBkGnd');