%%testMakeTrialStruct test script for makeTrialStruct function


session = 3;
subjectName = 'David';
nameOfTrialStruct = [subjectName,'Session',num2str(session),'_StdY_0_40_dY_0_01'];


makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantFixedBkGnd',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',true);


makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantBetweentrialBkGndVariation',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',true);

makeTrialStruct('directoryName','StimuliFixedFlatTargetShapeFixedIlluminantWithintrialBkGndVariation',...
    'LMSstructName', 'LMSStruct',...
    'outputFileName', nameOfTrialStruct,...
    'nBlocks', 30,...
    'stdYIndex', 6, ...
    'cmpYIndex', (1:11), ...
    'comparisionTargetSameSpectralShape',false);

