% Test script for the function drawPsychometricFunction

% Test script for the function drawPsychometricFunction
    drawPsychometricFunction('ExperimentType', 'Lightness',...
        'directoryName', 'StimuliFixedFlatTargetShapeFixedIlluminantFixedBkGnd', ...
        'subjectName', 'Vijay_StdY_0_40_dY_0_01_Trial_3', ...
        'date', '05-Nov-2018', ...
        'fileNumber', 1,...
        'thresholdU', 0.75, ...
        'thresholdL', 0.25);

% 
% drawPsychometricFunction('directoryName','RandomTargetShapeFixedIlluminantFixedBkGnd',...
%     'subjectName', 'testSubject',...
%     'fileNumber', 1);

