%%testMultispectralStructToLMSStruct Example to run multispectralStructToLMSStruct function

% multispectralStructToLMSStruct(...
%     'multipsectralStructFolder','StimuliRandomTargetShapeFixedIlluminantFixedBkGnd_dY0_01',...
%     'LMSStructFolder','RandomTargetShapeFixedIlluminantFixedBkGnd',...
%     'outputFileName','LMSStruct_dY0_01');

multispectralStructToLMSStruct(...
    'multipsectralStructFolder','FixedTargetShapeFixedIlluminantFixedBkGnd',...
    'LMSStructFolder','FixedTargetShapeFixedIlluminantFixedBkGnd',...
    'outputFileName','LMSStruct');