% Test script for the function drawPsychometricFunction

% Test script for the function drawPsychometricFunction
    drawPsychometricFunction('ExperimentType', 'Lightness',...
        'directoryName', 'RandomSameTargetFixedIlluminantFixedBkGnd', ...
        'subjectName', 'DavidSession1_StdY_0_40_dY_0_01', ...
        'date', '28-Nov-2017', ...
        'fileNumber', 1,...
        'thresholdU', 0.75, ...
        'thresholdL', 0.25);

% 
% drawPsychometricFunction('directoryName','RandomTargetShapeFixedIlluminantFixedBkGnd',...
%     'subjectName', 'testSubject',...
%     'fileNumber', 1);

