% Test script for the function drawPsychometricFunction

% Test script for the function drawPsychometricFunction
    drawPsychometricFunction('ExperimentType', 'Lightness',...
        'directoryName', 'RandomTargetShapeFixedIlluminantFixedBkGnd', ...
        'subjectName', 'VijayTest_40', ...
        'date', datestr(now,1), ...
        'fileNumber', 1,...
        'threshold', 0.75);

% 
% drawPsychometricFunction('directoryName','RandomTargetShapeFixedIlluminantFixedBkGnd',...
%     'subjectName', 'testSubject',...
%     'fileNumber', 1);

