function makeTrialStructForFinalExperiment(subjectName,iterationNumber, condition)

% This function makes trial structs for all cases.
%
% subjectName = Subject Name Ex. 'Vijay'
% iterationNumber = iteration number for the condition. Ex. 2
% condition = condition name. Ex. '2a'
%
% Vijay Singh wrote this. Dec 12 2018
% Vijay Singh updated this. Feb 21 2019
% Vijay Singh updated this. May 1 2019
% Vijay Singh updated this. Oct 7 2021


nameOfTrialStruct = [subjectName,'_Condition_',condition,'_Iteration_',num2str(iterationNumber)];

switch condition

    case '0_00'
        
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_00_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

    case '0_01'
        
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_01_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);
        
    case '0_03'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_03_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

    case '0_03_GrayBkg'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_03_GrayBkg_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

    case '0_10'
        
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_10_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);
        
    case '0_30'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_30_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);
        
    case '0_30_GrayBkg'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_0_30_GrayBkg_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

    case '1_00'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_1_00_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

    case '1_00_GrayBkg'
        makeTrialStruct('directoryName','StimuliCondition2_covScaleFactor_1_00_GrayBkg_NoReflection',...
            'LMSstructName', 'LMSStruct',...
            'outputFileName', nameOfTrialStruct,...
            'nBlocks', 30,...
            'stdYIndex', 6, ...
            'cmpYIndex', (1:11), ...
            'comparisionTargetSameSpectralShape',false);

        
        
end
end